!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.20.3)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinityasso(f2pysetupfunc)
      use yasso, only : mod5c
      external f2pysetupfunc
      call f2pysetupfunc(mod5c)
      end subroutine f2pyinityasso


